website/myapp/urls.py
from django.urls import path
from myapp.views import *

app_name = "myapp"

urlpatterns = [
    # path('', index, name="index"),
    path('', ProductListView.as_view(), name="index"),
# name нужно чтобы каждый раз не вводить путь url (index.html)
    path('<int:pk>/', ProductDetailView.as_view(), name="detail"),
    path('additem/', add_item, name="add_item"),
    path('udpateitem/<int:my_id>/', update_item, name="update_item"),
    # path('delete/<int:my_id>/', delete_item, name="delete_item"),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name="delete_item"),
]

website/myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, default='1')
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.TextField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images')

    def __str__(self):
        return self.name

website/myapp/views.py
from django.shortcuts import render, redirect
from .models import Product
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from django.views.generic import DeleteView
from django.urls import reverse_lazy

# def index(request):
#     items = Product.objects.all()
#     context = {
#         'items': items
#     }
    # return render(request, "myapp/index.html", context)

class ProductListView(ListView):
    model = Product
    template_name = "myapp/index.html"
    context_object_name = "items"
    paginate_by = 2


# Динамическая ссылка
# def indexItem(request, my_id):
#     item = Product.objects.get(id=my_id)
#     context = {
#         'item': item
#     }
#     return render(request, "myapp/detail.html", context)

class ProductDetailView(DetailView):
    model = Product
    template_name = "myapp/detail.html"
    context_object_name = "item"


@login_required
def add_item(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        image = request.FILES['upload']
        seller = request.user
        item = Product(name=name, price=price, description=description, image=image, seller=seller)
        item.save()
    return render(request, "myapp/additem.html")

def update_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == 'POST':
        item.name = request.POST.get("name")
        item.price = request.POST.get("price")
        item.description = request.POST.get("description")
        item.image = request.FILES.get('upload', item.image)
        item.save()
        return redirect("/myapp/")
    context = {
        'item': item
    }
    return render(request, "myapp/updateitem.html", context)

def delete_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == "POST":
        item.delete()
        return redirect("/myapp/")
    context = {
        'item': item
    }
    return render(request, "myapp/deleteitem.html", context)

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("myapp:index")

website/myapp/templates/myapp/additem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[500px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Add New Item Below</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Name..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Price..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Description..." name="description" id="description">
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Add Item</button>
        </div>
    </form>
</div>

{% endblock content %}

website/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
</head>
<body>
    
    {% include "myapp/navbar.html" %}
    {% block content %}
      TEXT
    {% endblock content %}
</body>
</html>

website/myapp/templates/myapp/deleteitem.html
{% extends "myapp/base.html" %}

{% block content %}
  <h1 class="text-2xl m-10 font bold">Delete Product</h1>
  <form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="post">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray text-sm font mb-2">Are you sure you want to delete this item</label>
        <label class="block text-gray text-sm font mb-2">{{ item.name}}</label>
        <img class="w-40 h-40" src="{{ item.image.url}}" alt="" srcset="">
    </div>
    <input class="bg-red-500 text-white px-5 py-2" type="submit" value="Confirm">
    <a class="button bg-green-500 text-white px-5 py-3" href="{% url 'myapp:index' %}">Cancel</a>
  </form>
{% endblock content %}

website/myapp/templates/myapp/detail.html
{% extends "myapp/base.html" %}
{% load humanize %}

{% block content %}
<h1>
  <div class="flex p-10 w-full h-200">
		<img class="w-1/3" src="{{ item.image.url }}" alt="itemPhoto">
		<div class="w-2/3 text-xl ml-10 mt-5">
			<p class="mt:5">{{ item.name }}</p>
			<p class="mt:5 text-green-500" >$ {{ item.price | intcomma}}</p>
			<p class="mt:5 text-gray-600">{{ item.description }}</p>
			<p class="mt:5 text-gray-600"><a href="{% url 'users:sellerprofile' item.id %}">@{{ item.seller }}</a></p>
			<p class="mt-5 text-gray-600">{{ item.seller.profile.contact_number }}</p>			
			<button class="bg-green-500 text-white mt-[50px]"><a href="{% url 'myapp:update_item' item.seller.id %}">Update Item</a></button>
			<button class="bg-red-500 text-white mt-[50px]"><a href="{% url 'myapp:delete_item' item.id %}">Delete Item</a></button>
		</div>
	</div>
</h1>
{% endblock content %}

website/myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}
{% load humanize %}
{% load static %}

{% block content %}

<main class="my-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
  <div class="sm:text-center lg:text-left">
    <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
      <span class="block xl:inline">Эсклюзивные товары</span>
      <span class="block xl:inline text-green-500">По Супер Ценам</span>
    </h1>
    <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl smLms-auto md:mt-5 md:text-xl lg:mx-0">Вы можете заказать товар из любой точки мира. Доставка включена</p>
  </div>
  <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap=3">
    {% for item in items %}
    <!-- Используем namespace : name -->
    <a href="{% url 'myapp:detail' item.id %}">
      <div class="rounded overflow-hidden shadow-lg">
        <img class="w-full h-[400px]" src="{{ item.image.url }}" alt="">
        <div class="px-6 py-4">
          <p class="font-bold text-xl mb-2">{{ item.name }}</p>
          <p class="font-bold text-xl text-green-500 mb-2">${{ item.price | intcomma }}</p>
          <p class="font-bold text-xl text-indogo-500 mb-2">by: {{ item.seller }}</p>
          <p class="text-gray-700 text-base">{{item.description}}</p>
        </div>
      </div>  
    </a>
    {% endfor %}
  </div>

  <div>
    <span>
      {% if page_obj.has_previous %}
        <a href="?page=1">First</a>
        <a href="?page={{ page_obj.previous_page_number}}">Previous</a>
      {% endif %}
    </span>

    <span>
      {{ page_obj }}
    </span>

    <span>
      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number}}">Next</a>
        <a href="?page={{ page_obj.paginator.num_pages}}">Last</a>
      {% endif %}
    </span>
  </div>

</main>


  

{% endblock content %}

website/myapp/templates/myapp/navbar.html
{% load static %}
<nav class="bg-white shadow-lg">
    <div class="max-w-6xl mx-auto px-4">
      <div class="flex justify-between">
        <div class="flex space-x-7">
          <div >
            <a href="{% url 'myapp:index' %}" class="flex items-center px-2 py-4">
            <img class="h-8 w-8" src="{% static 'myapp/images/shop.png' %}" alt="logo" />
            <span class="text-gray-500 font-semibold text-xl">Pro Shop</span>
          </a>
          </div>
          <div class="items-center flex space-x-1">
            <a href="{% url 'myapp:index' %}" class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
            <a href="{% url 'myapp:add_item' %}" class="py-4 px-2 text-gray-500 font-semibold">Add Item</a>
            <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contacts</a>
            {% if user.is_authenticated %}
              <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
              <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
              {% else %}
              <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:login' %}">Login</a>
            {% endif %}
          </div>
        </div>
      </div>
  </div>
</nav>

website/myapp/templates/myapp/product_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    <p>Do you want to delete {{ object}}</p>
    <input type="submit" value="Delete">
</form>

website/myapp/templates/myapp/updateitem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[500px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Update New Item Below</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value= "{{ item.name }}" type="text" placeholder="Name..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value= "{{ item.price }}" type="text" placeholder="Price..."  name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value= "{{ item.description }}" type="text" placeholder="Description..." name="description" id="description">
            <img class="w-20 h-20" src="{{ item.image.url }}" alt="">
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Update Item</button>
        </div>
    </form>
</div>

{% endblock content %}